### ISSUE TITLE
random supper large bubble

### ISSUE THREAD

**Issue by edeuss** [westdabestdb/bubble_bottom_bar#10]
Randomly with no changes my code th bubble became large. 
<img width="407" alt="Screen Shot 2019-04-07 at 8 49 57 PM" src="https://user-images.githubusercontent.com/13773566/55688319-6e6b0b00-5977-11e9-8933-73836839de19.png">

**Comment by westdabestdb** [comment]
Shit! How did you manage to achieve this? 😁 No worries, I'll push a nice update on Thursday. Sorry for that ugly wide af bubble ._.

**Comment by edeuss** [comment]
@westdabestdb I have no idea I just noticed it and I didn't mess with anything.

**Comment by edeuss** [comment]
Next Thursday @westdabestdb ?

**Comment by westdabestdb** [comment]
Hello, sorry for the delay. Here it is :) [https://github.com/westdabestdb/bubble_bottom_bar/blob/master/CHANGELOG.md#120](https://github.com/westdabestdb/bubble_bottom_bar/blob/master/CHANGELOG.md#120)
