### ISSUE TITLE
badge support

### ISSUE THREAD

**Issue by edeuss** [westdabestdb/bubble_bottom_bar#13]
Do you think its possible to add badge support to this package 
 from your other package. ? https://github.com/westdabestdb/bottom_navigation_badge

**Comment by westdabestdb** [comment]
Hey, I may do that soon, just came to my home country for vacation and currently spending time with family & food :) Thanks for the idea, I'll consider that and update this issue.

**Comment by edeuss** [comment]
any update @westdabestdb ?

**Comment by ponnamkarthik** [comment]
@westdabestdb check pr #23

**Comment by PonnamKarthik** [comment]
#23

**Comment by vincentderidder** [comment]
@westdabestdb Any update?

**Comment by vincentderidder** [comment]
@westdabestdb Could you merge @ponnamkarthik 's PR please?

**Comment by westdabestdb** [comment]
Hey guys, sorry for being two years late, been battling with shit. I'm merging some requests.

**Comment by westdabestdb** [comment]
Done.

**Comment by mahmoudatef925** [comment]
can't use badge ,, are you will upload another version .. i'm using   bubble_bottom_bar: ^1.2.0
also how can  i change BubbleBottomBarItem border radius 
thanks in advance 👍

**Comment by vincentderidder** [comment]
Replace `bubble_bottom_bar: ^1.2.0` with the following in your pubspec.yaml file to use the badges
```
bubble_bottom_bar: 
    git:
      url: git://github.com/westdabestdb/bubble_bottom_bar.git
```

**Comment by westdabestdb** [comment]
Will deploy newest version to pub tomorrow.
