### ISSUE TITLE
Notch background transparent 

### ISSUE THREAD

**Issue by job-46** [westdabestdb/bubble_bottom_bar#16]
How can i make the white part of the notch (as seen in the picture) be transparent? 

![Simulator Screen Shot - iPhone Xs - 2019-06-03 at 22 40 36](https://user-images.githubusercontent.com/9013404/58833286-f5272600-8650-11e9-973c-e5ae3f92ad5e.png)

**Comment by mintermania** [comment]
This helped me:
```
Scaffold(
   extendBody: true
);
```

**Comment by JotaFerreira** [comment]
when using extendBody: true, you will need to add bottom padding

**Comment by westdabestdb** [comment]
Marking this as solved.

**Comment by Fauzdar1** [comment]
Came for this, works. Thanks.
