### ISSUE TITLE
The method 'withOpacity' was called on null.

### ISSUE THREAD

**Issue by GioPan04** [westdabestdb/bubble_bottom_bar#17]
I just added the BubbleBottomBar and I get this error:

`
I/flutter (16409): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16409): The following NoSuchMethodError was thrown building _BottomNavigationTile(dirty):
I/flutter (16409): The method 'withOpacity' was called on null.
I/flutter (16409): Receiver: null
I/flutter (16409): Tried calling: withOpacity(0.2)
`
**Code:** 
`
bottomNavigationBar: BubbleBottomBar(
        opacity: .2,
        hasNotch: true,
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
        backgroundColor: Color.fromARGB(255, 62, 39, 35),
        elevation: 8,
        currentIndex: _cIndex,
        onTap: (int index) {
          setState(() {
            _cIndex = index;
          });
        },
        fabLocation: BubbleBottomBarFabLocation.end,
        items: <BubbleBottomBarItem>[
          BubbleBottomBarItem(title: Text("Test"), icon: Icon(Icons.book)),
          BubbleBottomBarItem(title: Text("Test"), icon: Icon(Icons.book)),
          BubbleBottomBarItem(title: Text("Test"), icon: Icon(Icons.book)),
          BubbleBottomBarItem(title: Text("Test"), icon: Icon(Icons.book)),
        ],
      )
`
or formated code [here](https://pastebin.com/R71sEvnT)

**Comment by westdabestdb** [comment]
Are you using the latest version ?

**Comment by GioPan04** [comment]
@westdabestdb Yes, I'm using 1.2.0

**Comment by arnemolland** [comment]
@GioPan-sh are you providing your BubbleBottomBarItem with a backgroundColor? A quick look at the source reveals that it's not defaulting to a non-null value, which would give you this exact error. I suggest that the property is either required or defaulting to a non-null value.

**Comment by GioPan04** [comment]
I forgot to close this issue 😅

**Comment by moyosolaa** [comment]
How did you solve this

**Comment by GioPan04** [comment]
> How did you solve this 

@Yosiwealth 
I added backgroundColor.

**Comment by GioPan04** [comment]
I'll make a PR to prevent this
