### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by HosseinBabriani** [westdabestdb/bubble_bottom_bar#19]
how can i use this plugin for rtl applications?

**Comment by iampato** [comment]
I believe this should help you
```
void main() {
  runApp(
    MaterialApp(
      home: Directionality( // add this
        textDirection: TextDirection.rtl, // set this property 
        child: HomePage(),
      ),
    ),
  );
}
```

it changes the text direction of the entire app, since Flutter 1.0 all material & cupertino widgets support RTL

**Comment by iampato** [comment]
@HosseinBabriani  @westdabestdb  I believe this should be closed

**Comment by westdabestdb** [comment]
@Iampato Thanks for letting me know.
