### ISSUE TITLE
Overly Aggressive Version Constraint

### ISSUE THREAD

**Issue by Andrewcpu** [westdabestdb/bubble_bottom_bar#3]
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because [proj name] depends on bubble_bottom_bar from git which requires SDK version >=2.1.0 <3.0.0, version solving failed.

**Comment by iusn** [comment]
I have the same issue

**Comment by Akshiiitsaxena** [comment]
Same Issue

**Comment by dylanmichaelryan** [comment]
Same Issue

**Comment by westdabestdb** [comment]
Hello, I apologize for late reply and support. I just added a new version with lower SDK version and dev channel support. Hopefully this will solve your issue.
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
```

**Comment by Andrewcpu** [comment]
Much appreciated! Thank you!
