### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by DevNico** [westdabestdb/bubble_bottom_bar#31]
Null safety is in the second technical preview stage with flutter core support it's therefore time to start migrating packages. I'd be happy to open a PR for Null Safety if it isn't already in the works.

**Comment by leynier** [comment]
Any update about this guys? I could help with this.

**Comment by leynier** [comment]
I see that `badges` dependency not have null safety support yet, but has a PR for this https://github.com/yako-dev/flutter_badges/pull/44

**Comment by mavyfaby** [comment]
There is a PR for this issue #34.
