### ISSUE TITLE
Overflowed Problem

### ISSUE THREAD

**Issue by mstfkhazaal** [westdabestdb/bubble_bottom_bar#32]
I have 6 BubbleBottomBarItem on the bottom navigation bar
When I run the text is incomplete and I get an error "Overflow by 0.968"

**Comment by westdabestdb** [comment]
Bottom navigation isn't meant to use more than 5 items. You may want to modify the code to achieve your approach. Check official guidelines at [https://material.io/components/bottom-navigation#usage](https://material.io/components/bottom-navigation#usage). Cheers.
