### ISSUE TITLE
Publish null-safety version on pub.dev

### ISSUE THREAD

**Issue by mavyfaby** [westdabestdb/bubble_bottom_bar#35]

**Comment by mavyfaby** [comment]
@westdabestdb

**Comment by westdabestdb** [comment]
Hey, sorry for late response, will do during the weekend.

**Comment by mavyfaby** [comment]
It's okay don't worry.

**Comment by ghost** [comment]
Thanks @westdabestdb 👍

**Comment by chitgoks** [comment]
update?

**Comment by mavyfaby** [comment]
Any?

**Comment by carlosfiori** [comment]
Any update?

**Comment by mikah22** [comment]
This is the only package that's holding up the migration of my project to Null Safety. I would appreciate if you could publish your version to pub.dev. Thank you so much for your contribution, you are the best.

**Comment by chitgoks** [comment]
i ju copied his code inst3ad in and made it null safety

**Comment by mavyfaby** [comment]
> This is the only package that's holding up the migration of my project to Null Safety. I would appreciate if you could publish your version to pub.dev. Thank you so much for your contribution, you are the best.

I'll try later

**Comment by mikah22** [comment]
Since the dev is not responding, I have now just pointed my pubspec dependency to this Git repository. :-(

**Comment by justkawal** [comment]
I'll be giving the null-safety support to this package today

**Comment by westdabestdb** [comment]
Apologies for my absence. I just published the null safety version on the pub.
