### ISSUE TITLE
Still need some refinement for the animation 

### ISSUE THREAD

**Issue by sooxt98** [westdabestdb/bubble_bottom_bar#4]
https://dribbble.com/shots/5925052-Google-Bottom-Bar-Navigation-Pattern
As you can see, the first tab icon animation behave differently from the dribbble.

**Comment by westdabestdb** [comment]
Hello, can you please describe how the first tab is different? Also I build the package from [this design](https://www.instagram.com/p/BtyUbSkBlnF/?utm_source=ig_share_sheet&igshid=1c7v735400hxp).

**Comment by sooxt98** [comment]
Sorry for late reply, this is what I mean

> There are some misalignment on the first icon.

![image](https://user-images.githubusercontent.com/13378059/53758685-655ec800-3ef9-11e9-99af-557aa6b9ef8a.png)

**Comment by sooxt98** [comment]
@westdabestdb any updates?

**Comment by westdabestdb** [comment]
Will look into it! Currently too sick to code :/

**Comment by westdabestdb** [comment]
Hello, I had the animations refactored and released in v1.0.2. You can preview it [here](https://imgur.com/hOZ2ipl) and the animations are sightly better.

**Comment by sooxt98** [comment]
Hmmm the obvious thing is the first icon still slightly offset while interacting with it. Keep it up 🔥🔥🔥🔥 seems like just only left the individual icon button movement .
