### ISSUE TITLE
Example with FAB button?

### ISSUE THREAD

**Issue by udiedrichsen** [westdabestdb/bubble_bottom_bar#8]
Can please provide an example with a fab button?

**Comment by westdabestdb** [comment]
Of course, I was little busy yesterday, but will do it today!

**Comment by jagged91** [comment]
Agreed! I can't figure out how to add the FAB - there's no reference to it in the BubbleBottomBar class other than its location!

**Comment by DevTard** [comment]
@jgadsby @udiedrichsen  If you want to add a fab add this code to your scaffold:

```flutter
floatingActionButton: FloatingActionButton(onPressed: (){}, child: Icon(Icons.add), ),
floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
```
then make sure the same settings are being used in the bottom bar:
```flutter
fabLocation: BubbleBottomBarFabLocation.end,
```

Hope this helps

**Comment by jagged91** [comment]
Awesome, thanks guys!

**Comment by westdabestdb** [comment]
@DevTard Thank you for covering me! I'm dealing with multiple deadlines & final exams so couldn't have time to look up here.

**Comment by westdabestdb** [comment]
Hello everybody! Thank you for using the package. I pushed a new update to example app, which now has fab code. Check it [in this commit](https://github.com/westdabestdb/bubble_bottom_bar/commit/ada664df2cf8c40ae28e5ac744b9107da51eb0db#diff-d9a718a3042c2ebab14df5f34ef46a52).
